[versions]
agp = "8.7.2"
multidex= "2.0.1"
kotlin = "1.9.24"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
gson = "2.8.0"
smartRefresh = "2.1.0"
adapterHelper = "3.0.1"
flexibledividerVersion = "1.4.0"
flycoTabLayout = "3.0.0"
googleAdid = "18.1.0"
googleLocation = "21.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
smartRefresh = { group = "io.github.scwang90", name = "refresh-layout-kernel", version.ref = "smartRefresh" }
smartRefreshHeader = { group = "io.github.scwang90", name = "refresh-header-classics", version.ref = "smartRefresh" }
smartRefreshFooter = { group = "io.github.scwang90", name = "refresh-footer-classics", version.ref = "smartRefresh" }
baseRecyclerViewAdapterHelper = { group = "com.github.CymChad", name = "BaseRecyclerViewAdapterHelper", version.ref = "adapterHelper" }
flexibledivider = { group = "com.yqritc", name = "recyclerview-flexibledivider", version.ref = "flexibledividerVersion" }
flycoTabLayout = { group = "io.github.h07000223", name = "flycoTabLayout", version.ref = "flycoTabLayout" }
googleAdid = { group = "com.google.android.gms", name = "play-services-ads-identifier", version.ref = "googleAdid" }
googleLocation = { group = "com.google.android.gms", name = "play-services-location", version.ref = "googleLocation" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

